# Split up a Train and Test Dataset of Tweets by Female Annotators

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import mode

## 1. Read and Modify Dataset

In [2]:
## Damians Code
# read annotations
df = pd.read_csv('../data/annotations/twitter_klimaat_discussie_coderingen.csv')
# merge in tweet texts
#tweets = pd.read_csv('../retrieve-tweets/klimaatgesprekken-eerste-mag-geen-at-bevatten-clean.csv')
tweets = pd.read_csv('../retrieve-tweets/klimaatgesprekken-clean.csv')
tweets = tweets.rename({'conversationid':"tweet_id", 'tweetorder':'comment_nr'}, axis=1)
df = df.merge(tweets, on=['tweet_id', 'comment_nr'], how='left')
# some data wrangling
# not considering incomplete rows
_l1 = len(df)
df.dropna(inplace=True)
print(f"Dropped {_l1-len(df)} of {_l1} rows due to missing values. New number of rows: {len(df)}")
df.rename(lambda x: x.replace('.','_'), axis=1, inplace=True)
df['tweet_id_comment_nr'] = df['tweet_id'].map(str) + "_" +  df['comment_nr'].map(str)
df.insert(list(df.columns).index('education'), 'higher_education', df.education.map(lambda x: int(x.startswith("Hoger") or x.startswith("Wetenschappelijk"))))

# recode textual labels to 0 and 1
#def customrecode(x):
#    if 'geen' in x.lower():
#        return False
#    elif 'oneens' in x.lower():
#        return False
#    else:
#        return True

#df.loc[:,[e for e in df.columns if e.startswith('comment_') and not e=='comment_nr']] = \
#    df.loc[:,[e for e in df.columns if e.startswith('comment_') and not e=='comment_nr']].map(customrecode)

df['comment_inhoudelijk_argument_binary'] = df['comment_inhoudelijk_argument'].map(lambda x: int(x=="Inhoudelijk argument"))
df['comment_persoonlijke_aanval_binary'] = df['comment_persoonlijke_aanval'].map(lambda x: int(x=="Persoonlijke aanval"))
df['comment_respectvol_binary'] = df['comment_respectvol'].map(lambda x: int(x=="Eens"))

Dropped 361 of 42844 rows due to missing values. New number of rows: 42483

In [3]:
df

,coder,jobset,scientific_consensus_pro_klimaat,scientific_consensus_belangrijk_onderwerp,scientific_consensus_sterke_mening,scientific_consensus_interesse_klimaat,age,gender,higher_education,education,...,comment_inhoudelijk_argument,comment_persoonlijke_aanval,comment_over_communicatie,comment_respectvol,id,text,tweet_id_comment_nr,comment_inhoudelijk_argument_binary,comment_persoonlijke_aanval_binary,comment_respectvol_binary
0,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,0,Voorbereidend of kort middelbaar beroepsonderw...,...,Inhoudelijk argument,Persoonlijke aanval,Oneens,Oneens,11_22_1,@USER Men riep hier jaren te schreeuwen over '...,22_1,1,1,0
1,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,0,Voorbereidend of kort middelbaar beroepsonderw...,...,Inhoudelijk argument,Persoonlijke aanval,Eens,Oneens,11_22_2,"@USER Je wou zeggen ""Is het een koude dag, het...",22_2,1,1,0
2,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,0,Voorbereidend of kort middelbaar beroepsonderw...,...,Geen inhoudelijk argument,Geen persoonlijke aanval,Eens,Oneens,11_22_3,@USER Hij praat trouwens onzin want ik heb hie...,22_3,0,0,0
3,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,0,Voorbereidend of kort middelbaar beroepsonderw...,...,Inhoudelijk argument,Persoonlijke aanval,Eens,Eens,11_22_4,@USER Er zijn ongetwijfeld ook mensen met stad...,22_4,1,1,1
4,11,set_3,3.0,4.0,5.0,5.0,30.0,Vrouw,0,Voorbereidend of kort middelbaar beroepsonderw...,...,Inhoudelijk argument,Geen persoonlijke aanval,Oneens,Eens,11_22_5,"@USER Nu woon ik ver van grote steden af, niet...",22_5,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42839,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,1,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",...,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_1,@USER Hoezo zelf gemaakt,378_1,0,0,0
42840,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,1,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",...,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_2,@USER Zijn neefje!!,378_2,0,0,0
42841,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,1,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",...,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_3,"@USER Netjes roch, slim ventje",378_3,0,0,0
42842,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,1,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",...,Geen inhoudelijk argument,Geen persoonlijke aanval,Oneens,Oneens,2588_378_4,@USER Op zijn kop helaas,378_4,0,0,0
42843,2588,set_44,6.0,7.0,6.0,6.0,22.0,Vrouw,1,"Hoger beroepsonderwijs (HBO, HTS, HEAO, Social...",...,Geen inhoudelijk argument,Persoonlijke aanval,Oneens,Eens,2588_378_5,"@USER Goed kijken, deuger",378_5,0,1,1

In [4]:
list(df)

['coder',
 'jobset',
 'scientific_consensus_pro_klimaat',
 'scientific_consensus_belangrijk_onderwerp',
 'scientific_consensus_sterke_mening',
 'scientific_consensus_interesse_klimaat',
 'age',
 'gender',
 'higher_education',
 'education',
 'workhours',
 'tweet_id',
 'tweet_pro_klimaat',
 'comment_nr',
 'comment_pro_klimaat',
 'comment_inhoudelijk_argument',
 'comment_persoonlijke_aanval',
 'comment_over_communicatie',
 'comment_respectvol',
 'id',
 'text',
 'tweet_id_comment_nr',
 'comment_inhoudelijk_argument_binary',
 'comment_persoonlijke_aanval_binary',
 'comment_respectvol_binary']

In [5]:
len(df.tweet_id_comment_nr.unique()) # Nr of annotated Tweets (IDs)

2004

In [6]:
len(df.coder.unique()) # Nr of Coders

1504

In [7]:
# Reduce dataset to needed columns
df_red = df[['id',"tweet_id_comment_nr", "text","coder", "gender", "comment_pro_klimaat",
             "comment_respectvol_binary", "comment_inhoudelijk_argument_binary",'comment_persoonlijke_aanval_binary']]
df_red

,id,tweet_id_comment_nr,text,coder,gender,comment_pro_klimaat,comment_respectvol_binary,comment_inhoudelijk_argument_binary,comment_persoonlijke_aanval_binary
0,11_22_1,22_1,@USER Men riep hier jaren te schreeuwen over '...,11,Vrouw,Ja,0,1,1
1,11_22_2,22_2,"@USER Je wou zeggen ""Is het een koude dag, het...",11,Vrouw,Ja,0,1,1
2,11_22_3,22_3,@USER Hij praat trouwens onzin want ik heb hie...,11,Vrouw,Ja,0,0,0
3,11_22_4,22_4,@USER Er zijn ongetwijfeld ook mensen met stad...,11,Vrouw,Neutraal,1,1,1
4,11_22_5,22_5,"@USER Nu woon ik ver van grote steden af, niet...",11,Vrouw,Neutraal,1,1,0
...,...,...,...,...,...,...,...,...,...
42839,2588_378_1,378_1,@USER Hoezo zelf gemaakt,2588,Vrouw,Nee,0,0,0
42840,2588_378_2,378_2,@USER Zijn neefje!!,2588,Vrouw,Nee,0,0,0
42841,2588_378_3,378_3,"@USER Netjes roch, slim ventje",2588,Vrouw,Nee,0,0,0
42842,2588_378_4,378_4,@USER Op zijn kop helaas,2588,Vrouw,Nee,0,0,0
42843,2588_378_5,378_5,"@USER Goed kijken, deuger",2588,Vrouw,Nee,1,0,1

## 2. Make A Female Subsamples

In [8]:
df_female = df_red[df_red['gender'] == "Vrouw"]
df_female

,id,tweet_id_comment_nr,text,coder,gender,comment_pro_klimaat,comment_respectvol_binary,comment_inhoudelijk_argument_binary,comment_persoonlijke_aanval_binary
0,11_22_1,22_1,@USER Men riep hier jaren te schreeuwen over '...,11,Vrouw,Ja,0,1,1
1,11_22_2,22_2,"@USER Je wou zeggen ""Is het een koude dag, het...",11,Vrouw,Ja,0,1,1
2,11_22_3,22_3,@USER Hij praat trouwens onzin want ik heb hie...,11,Vrouw,Ja,0,0,0
3,11_22_4,22_4,@USER Er zijn ongetwijfeld ook mensen met stad...,11,Vrouw,Neutraal,1,1,1
4,11_22_5,22_5,"@USER Nu woon ik ver van grote steden af, niet...",11,Vrouw,Neutraal,1,1,0
...,...,...,...,...,...,...,...,...,...
42839,2588_378_1,378_1,@USER Hoezo zelf gemaakt,2588,Vrouw,Nee,0,0,0
42840,2588_378_2,378_2,@USER Zijn neefje!!,2588,Vrouw,Nee,0,0,0
42841,2588_378_3,378_3,"@USER Netjes roch, slim ventje",2588,Vrouw,Nee,0,0,0
42842,2588_378_4,378_4,@USER Op zijn kop helaas,2588,Vrouw,Nee,0,0,0
42843,2588_378_5,378_5,"@USER Goed kijken, deuger",2588,Vrouw,Nee,1,0,1

## 3. Pivot the Dataset and get majority votes for all dependend variables

### 3.1 Respect

In [9]:
# Step 1: Add a counter for each annotation per text_id
df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

# Step 2: Pivot the DataFrame so each annotation becomes a column
df_wide = df_female.pivot(index='tweet_id_comment_nr', columns='annotation_num', values='comment_respectvol_binary')

# Step 3: Reset index and rename columns (optional)
df_wide.columns = [f'annotation_{i}' for i in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 4: (Optional) Merge the original text back in if needed
# Get one copy of each text
text_lookup = df[['tweet_id_comment_nr', 'text']].drop_duplicates(subset='tweet_id_comment_nr')
df_female_respect = df_wide.merge(text_lookup, on='tweet_id_comment_nr', how='left')

# Final result
df_female_respect

/var/folders/tb/jk3qktsn6kb2n8ngl_mqxpqw0000gp/T/ipykernel_14071/3289040146.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

,tweet_id_comment_nr,annotation_1,annotation_2,annotation_3,annotation_4,annotation_5,annotation_6,annotation_7,annotation_8,annotation_9,...,annotation_19,annotation_20,annotation_21,annotation_22,annotation_23,annotation_24,annotation_25,annotation_26,annotation_27,text
0,100_1,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...
1,100_2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Geen referendum meer hè, welke partijen ..."
2,100_3,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Hoeveel zetels hebben ""linkse"" partijen?..."
3,100_4,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Maar de vraag is: Heeft Myrthe's partij ...
4,100_5,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER ""Dus Lodewijk treedt af vanwege de toesl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999,9_1,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Als jullie nog banen zoeken. Er ligt nog...
2000,9_2,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Waar op de Volendamlaan is dit precies? ...
2001,9_3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Op de hoek bij de Heiloostraat waar het ...
2002,9_4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Bedankt voor de snelle reactie. Geven we...
2003,9_5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Ook bedankt

In [10]:
# Count non-NaN annotations across annotation columns
annotation_cols = [col for col in df_female_respect.columns if col.startswith('annotation_')]

df_female_respect['num_valid_annotations'] = df_female_respect[annotation_cols].notna().sum(axis=1)

# Compute row-wise mode (majority vote)
def majority_vote(row):
    values = row[annotation_cols].dropna()
    if len(values) == 0:
        return np.nan
    return values.mode().iloc[0]  # mode() returns a Series

df_female_respect['majority_vote_respect'] = df_female_respect.apply(majority_vote, axis=1)
df_female_respect.head()

,tweet_id_comment_nr,annotation_1,annotation_2,annotation_3,annotation_4,annotation_5,annotation_6,annotation_7,annotation_8,annotation_9,...,annotation_21,annotation_22,annotation_23,annotation_24,annotation_25,annotation_26,annotation_27,text,num_valid_annotations,majority_vote_respect
0,100_1,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...,11,1.0
1,100_2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Geen referendum meer hè, welke partijen ...",11,1.0
2,100_3,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",11,0.0
3,100_4,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Maar de vraag is: Heeft Myrthe's partij ...,11,1.0
4,100_5,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",11,1.0

In [11]:
df_female_respect['majority_vote_respect'].value_counts()

1.0    1530
0.0     474
Name: majority_vote_respect, dtype: int64

In [12]:
df_female_respect_red = df_female_respect[["tweet_id_comment_nr","text",'majority_vote_respect']]
df_female_respect_red

,tweet_id_comment_nr,text,majority_vote_respect
0,100_1,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...,1.0
1,100_2,"@USER Geen referendum meer hè, welke partijen ...",1.0
2,100_3,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",0.0
3,100_4,@USER Maar de vraag is: Heeft Myrthe's partij ...,1.0
4,100_5,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",1.0
...,...,...,...
1999,9_1,@USER Als jullie nog banen zoeken. Er ligt nog...,0.0
2000,9_2,@USER Waar op de Volendamlaan is dit precies? ...,1.0
2001,9_3,@USER Op de hoek bij de Heiloostraat waar het ...,1.0
2002,9_4,@USER Bedankt voor de snelle reactie. Geven we...,1.0
2003,9_5,@USER Ook bedankt,1.0

### 3.2 Attack

In [13]:
# Step 1: Add a counter for each annotation per text_id
df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

# Step 2: Pivot the DataFrame so each annotation becomes a column
df_wide = df_female.pivot(index='tweet_id_comment_nr', columns='annotation_num', values='comment_persoonlijke_aanval_binary')

# Step 3: Reset index and rename columns (optional)
df_wide.columns = [f'annotation_{i}' for i in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 4: (Optional) Merge the original text back in if needed
# Get one copy of each text
text_lookup = df[['tweet_id_comment_nr', 'text']].drop_duplicates(subset='tweet_id_comment_nr')
df_female_attack = df_wide.merge(text_lookup, on='tweet_id_comment_nr', how='left')

# Compute row-wise mode (majority vote)
def majority_vote(row):
    values = row[annotation_cols].dropna()
    if len(values) == 0:
        return np.nan
    return values.mode().iloc[0]  # mode() returns a Series

df_female_attack['majority_vote_attack'] = df_female_attack.apply(majority_vote, axis=1)
df_female_attack.head()

/var/folders/tb/jk3qktsn6kb2n8ngl_mqxpqw0000gp/T/ipykernel_14071/851092349.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

,tweet_id_comment_nr,annotation_1,annotation_2,annotation_3,annotation_4,annotation_5,annotation_6,annotation_7,annotation_8,annotation_9,...,annotation_20,annotation_21,annotation_22,annotation_23,annotation_24,annotation_25,annotation_26,annotation_27,text,majority_vote_attack
0,100_1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...,0.0
1,100_2,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Geen referendum meer hè, welke partijen ...",0.0
2,100_3,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",1.0
3,100_4,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Maar de vraag is: Heeft Myrthe's partij ...,1.0
4,100_5,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",1.0

In [14]:
df_female_attack['majority_vote_attack'].value_counts()

0.0    1532
1.0     472
Name: majority_vote_attack, dtype: int64

In [16]:
df_female_attack_red = df_female_attack[["tweet_id_comment_nr",'majority_vote_attack']]
df_female_attack_red

     tweet_id_comment_nr  majority_vote_attack
0                  100_1                   0.0
1                  100_2                   0.0
2                  100_3                   1.0
3                  100_4                   1.0
4                  100_5                   1.0
...                  ...                   ...
1999                 9_1                   1.0
2000                 9_2                   0.0
2001                 9_3                   0.0
2002                 9_4                   0.0
2003                 9_5                   0.0

[2004 rows x 2 columns]

### 3.3 Argument

In [18]:
# Step 1: Add a counter for each annotation per text_id
df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

# Step 2: Pivot the DataFrame so each annotation becomes a column
df_wide = df_female.pivot(index='tweet_id_comment_nr', columns='annotation_num', values='comment_inhoudelijk_argument_binary')

# Step 3: Reset index and rename columns (optional)
df_wide.columns = [f'annotation_{i}' for i in df_wide.columns]
df_wide = df_wide.reset_index()

# Step 4: (Optional) Merge the original text back in if needed
# Get one copy of each text
text_lookup = df[['tweet_id_comment_nr', 'text']].drop_duplicates(subset='tweet_id_comment_nr')
df_female_argument = df_wide.merge(text_lookup, on='tweet_id_comment_nr', how='left')

# Compute row-wise mode (majority vote)
def majority_vote(row):
    values = row[annotation_cols].dropna()
    if len(values) == 0:
        return np.nan
    return values.mode().iloc[0]  # mode() returns a Series

df_female_argument['majority_vote_argument'] = df_female_attack.apply(majority_vote, axis=1)
df_female_argument.head()

/var/folders/tb/jk3qktsn6kb2n8ngl_mqxpqw0000gp/T/ipykernel_14071/2448063062.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_female['annotation_num'] = df_female.groupby('tweet_id_comment_nr').cumcount() + 1

,tweet_id_comment_nr,annotation_1,annotation_2,annotation_3,annotation_4,annotation_5,annotation_6,annotation_7,annotation_8,annotation_9,...,annotation_20,annotation_21,annotation_22,annotation_23,annotation_24,annotation_25,annotation_26,annotation_27,text,majority_vote_argument
0,100_1,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...,0.0
1,100_2,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Geen referendum meer hè, welke partijen ...",0.0
2,100_3,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",0.0
3,100_4,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,@USER Maar de vraag is: Heeft Myrthe's partij ...,1.0
4,100_5,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",0.0

In [19]:
df_female_argument['majority_vote_argument'].value_counts()

0.0    1104
1.0     900
Name: majority_vote_argument, dtype: int64

In [21]:
df_female_argument_red = df_female_argument[["tweet_id_comment_nr",'majority_vote_argument']]
df_female_argument_red

     tweet_id_comment_nr  majority_vote_argument
0                  100_1                     0.0
1                  100_2                     0.0
2                  100_3                     0.0
3                  100_4                     1.0
4                  100_5                     0.0
...                  ...                     ...
1999                 9_1                     0.0
2000                 9_2                     1.0
2001                 9_3                     1.0
2002                 9_4                     1.0
2003                 9_5                     0.0

[2004 rows x 2 columns]

### 3.4 Concat

In [25]:
df_female_final = df_female_respect_red.merge(df_female_attack_red, on='tweet_id_comment_nr', how='outer') \
            .merge(df_female_argument_red, on='tweet_id_comment_nr', how='outer')
df_female_final

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument
0,100_1,@USER https://t.co/XoAEGSbThS https://t.co/U7Z...,1.0,0.0,0.0
1,100_2,"@USER Geen referendum meer hè, welke partijen ...",1.0,0.0,0.0
2,100_3,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",0.0,1.0,0.0
3,100_4,@USER Maar de vraag is: Heeft Myrthe's partij ...,1.0,1.0,1.0
4,100_5,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",1.0,1.0,0.0
...,...,...,...,...,...
1999,9_1,@USER Als jullie nog banen zoeken. Er ligt nog...,0.0,1.0,0.0
2000,9_2,@USER Waar op de Volendamlaan is dit precies? ...,1.0,0.0,1.0
2001,9_3,@USER Op de hoek bij de Heiloostraat waar het ...,1.0,0.0,1.0
2002,9_4,@USER Bedankt voor de snelle reactie. Geven we...,1.0,0.0,1.0
2003,9_5,@USER Ook bedankt,1.0,0.0,0.0

## 4. Short Text Cleansing Session

In [26]:
# Get rid the @USER handle
df_female_final['text_cleaned_01'] = df_female_final['text'].str.replace(r'@USER', '', regex=True).str.strip()

In [27]:
# Get rid of URLs 
df_female_final['text_cleaned_02'] = df_female_final['text_cleaned_01'].str.replace(r'http\S+', '', regex=True).str.strip()

In [28]:
# Get rid of very short terms, such as ja, Dito., !! 
low_content_pattern = r'^\s*([a-zA-Z]{1,4}|[!?.,]{1,})\s*$'
df_female_final = df_female_final[~df_female_final['text_cleaned_02'].str.match(low_content_pattern, na=False)]

In [29]:
# Remove now empty cells
df_female_final = df_female_final[df_female_final['text_cleaned_02'].str.strip().astype(bool)]
len(df_female_final)

1950

In [31]:
df_female_final

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
1,100_2,"@USER Geen referendum meer hè, welke partijen ...",1.0,0.0,0.0,"Geen referendum meer hè, welke partijen hebben...","Geen referendum meer hè, welke partijen hebben..."
2,100_3,"@USER Hoeveel zetels hebben ""linkse"" partijen?...",0.0,1.0,0.0,"Hoeveel zetels hebben ""linkse"" partijen?\nWe (...","Hoeveel zetels hebben ""linkse"" partijen?\nWe (..."
3,100_4,@USER Maar de vraag is: Heeft Myrthe's partij ...,1.0,1.0,1.0,Maar de vraag is: Heeft Myrthe's partij PvdA n...,Maar de vraag is: Heeft Myrthe's partij PvdA n...
4,100_5,"@USER ""Dus Lodewijk treedt af vanwege de toesl...",1.0,1.0,0.0,"""Dus Lodewijk treedt af vanwege de toeslagenaf...","""Dus Lodewijk treedt af vanwege de toeslagenaf..."
5,101_1,"@USER Beste Brink, wat ik altijd mis bij klima...",0.0,1.0,0.0,"Beste Brink, wat ik altijd mis bij klimaatdwaz...","Beste Brink, wat ik altijd mis bij klimaatdwaz..."
...,...,...,...,...,...,...,...
1999,9_1,@USER Als jullie nog banen zoeken. Er ligt nog...,0.0,1.0,0.0,Als jullie nog banen zoeken. Er ligt nog een b...,Als jullie nog banen zoeken. Er ligt nog een b...
2000,9_2,@USER Waar op de Volendamlaan is dit precies? ...,1.0,0.0,1.0,Waar op de Volendamlaan is dit precies? Dan ge...,Waar op de Volendamlaan is dit precies? Dan ge...
2001,9_3,@USER Op de hoek bij de Heiloostraat waar het ...,1.0,0.0,1.0,Op de hoek bij de Heiloostraat waar het kerstb...,Op de hoek bij de Heiloostraat waar het kerstb...
2002,9_4,@USER Bedankt voor de snelle reactie. Geven we...,1.0,0.0,1.0,Bedankt voor de snelle reactie. Geven we metee...,Bedankt voor de snelle reactie. Geven we metee...
2003,9_5,@USER Ook bedankt,1.0,0.0,0.0,Ook bedankt,Ook bedankt

In [32]:
df_female_final.to_csv("df_female_complete.csv", index=None)

## 5. Split into tarin and test sample

In [33]:
from sklearn.model_selection import train_test_split

df_female_train, df_female_test = train_test_split(df_female_final, test_size=0.2, random_state=1990, shuffle=True)

In [34]:
df_female_train

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
189,151_2,@USER Waarin Natalie en Nigel de wereld bespre...,1.0,0.0,0.0,Waarin Natalie en Nigel de wereld bespreken en...,Waarin Natalie en Nigel de wereld bespreken en...
414,203_5,@USER Klimaatwetenschappers hebben een ander v...,1.0,0.0,1.0,Klimaatwetenschappers hebben een ander vakgebi...,Klimaatwetenschappers hebben een ander vakgebi...
902,349_5,@USER @USER @USER En verder wordt er gezegd da...,1.0,0.0,1.0,En verder wordt er gezegd dat vervuiling een b...,En verder wordt er gezegd dat vervuiling een b...
768,311_5,@USER Hoi Marien. Bedoeld voor de GroenLinks. ...,1.0,1.0,1.0,Hoi Marien. Bedoeld voor de GroenLinks. Zie he...,Hoi Marien. Bedoeld voor de GroenLinks. Zie he...
25,105_4,@USER Zeker. En anders exporteren we dat spul ...,1.0,0.0,0.0,Zeker. En anders exporteren we dat spul naar A...,Zeker. En anders exporteren we dat spul naar A...
...,...,...,...,...,...,...,...
566,252_1,@USER Natuurlijk wel.,0.0,0.0,0.0,Natuurlijk wel.,Natuurlijk wel.
889,347_3,"@USER Broeikaseffect, lang niet meer gehoord 😃...",1.0,0.0,1.0,"Broeikaseffect, lang niet meer gehoord 😃\n\nIk...","Broeikaseffect, lang niet meer gehoord 😃\n\nIk..."
556,249_2,@USER Ik vind discussies over Media Bias waard...,1.0,0.0,1.0,"Ik vind discussies over Media Bias waardevol, ...","Ik vind discussies over Media Bias waardevol, ..."
991,367_2,@USER Dat staat in het artikel. Plantengroei e...,1.0,0.0,1.0,Dat staat in het artikel. Plantengroei explode...,Dat staat in het artikel. Plantengroei explode...
118,124_8,"@USER Zeker, #au!",1.0,0.0,0.0,"Zeker, #au!","Zeker, #au!"

In [35]:
df_female_test

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
787,316_7,"@USER @USER Over 6 jaar 1,5⁰, zó heftig? Dan z...",1.0,0.0,1.0,"Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie...","Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie..."
1454,479_1,@USER Dat punt van die klimaatverandering is n...,1.0,0.0,0.0,Dat punt van die klimaatverandering is nu wel ...,Dat punt van die klimaatverandering is nu wel ...
188,151_1,@USER Ik voel een nieuw podcast opkomen: “Mijn...,1.0,0.0,0.0,Ik voel een nieuw podcast opkomen: “Mijn kappe...,Ik voel een nieuw podcast opkomen: “Mijn kappe...
766,311_3,@USER Zaterdagochtend 12-2-22. Blauwe lucht. V...,1.0,0.0,1.0,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...
1603,513_7,@USER @USER klimaatontkenner=#misinformatie ht...,0.0,0.0,0.0,klimaatontkenner=#misinformatie https://t.co/I...,klimaatontkenner=#misinformatie
...,...,...,...,...,...,...,...
558,249_4,"@USER Muah, ik weet niet of dat zo is. Ik heb ...",1.0,0.0,1.0,"Muah, ik weet niet of dat zo is. Ik heb veel s...","Muah, ik weet niet of dat zo is. Ik heb veel s..."
1701,550_4,"@USER @USER @USER Utopisme en activisme, daare...",1.0,0.0,0.0,"Utopisme en activisme, daarentegen, lijken voo...","Utopisme en activisme, daarentegen, lijken voo..."
1635,524_5,@USER Beter ten halve gekeerd hoor…🤔😀,1.0,0.0,1.0,Beter ten halve gekeerd hoor…🤔😀,Beter ten halve gekeerd hoor…🤔😀
1783,568_8,@USER @USER @USER In alle grote kranten wordt ...,1.0,1.0,1.0,In alle grote kranten wordt klimaatverandering...,In alle grote kranten wordt klimaatverandering...
415,204_1,@USER @USER Hier heb je ruim 31 duizend rockst...,0.0,0.0,0.0,Hier heb je ruim 31 duizend rocksterren:\nhttp...,Hier heb je ruim 31 duizend rocksterren:\n\nHo...

In [36]:
df_female_train.to_csv("df_female_train.csv", index=None)

In [37]:
df_female_test.to_csv("df_female_test.csv", index=None)

# Done