# Bootsrap and Make Classifier Female Respect tbc

In [10]:
import pandas as pd
import numpy as np

## 1. Read Female Train Set

In [3]:
df_female_train = pd.read_csv("df_female_train.csv")
df_female_train

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
0,151_2,@USER Waarin Natalie en Nigel de wereld bespre...,1.0,0.0,0.0,Waarin Natalie en Nigel de wereld bespreken en...,Waarin Natalie en Nigel de wereld bespreken en...
1,203_5,@USER Klimaatwetenschappers hebben een ander v...,1.0,0.0,1.0,Klimaatwetenschappers hebben een ander vakgebi...,Klimaatwetenschappers hebben een ander vakgebi...
2,349_5,@USER @USER @USER En verder wordt er gezegd da...,1.0,0.0,1.0,En verder wordt er gezegd dat vervuiling een b...,En verder wordt er gezegd dat vervuiling een b...
3,311_5,@USER Hoi Marien. Bedoeld voor de GroenLinks. ...,1.0,1.0,1.0,Hoi Marien. Bedoeld voor de GroenLinks. Zie he...,Hoi Marien. Bedoeld voor de GroenLinks. Zie he...
4,105_4,@USER Zeker. En anders exporteren we dat spul ...,1.0,0.0,0.0,Zeker. En anders exporteren we dat spul naar A...,Zeker. En anders exporteren we dat spul naar A...
...,...,...,...,...,...,...,...
1555,252_1,@USER Natuurlijk wel.,0.0,0.0,0.0,Natuurlijk wel.,Natuurlijk wel.
1556,347_3,"@USER Broeikaseffect, lang niet meer gehoord 😃...",1.0,0.0,1.0,"Broeikaseffect, lang niet meer gehoord 😃\n\nIk...","Broeikaseffect, lang niet meer gehoord 😃\n\nIk..."
1557,249_2,@USER Ik vind discussies over Media Bias waard...,1.0,0.0,1.0,"Ik vind discussies over Media Bias waardevol, ...","Ik vind discussies over Media Bias waardevol, ..."
1558,367_2,@USER Dat staat in het artikel. Plantengroei e...,1.0,0.0,1.0,Dat staat in het artikel. Plantengroei explode...,Dat staat in het artikel. Plantengroei explode...
1559,124_8,"@USER Zeker, #au!",1.0,0.0,0.0,"Zeker, #au!","Zeker, #au!"

## 2. Bootsstrap samples for few-shot learning

### 2.1 Respect

In [6]:
df_female_train_respect = df_female_train[["tweet_id_comment_nr","text_cleaned_02",'majority_vote_respect']]
df_female_train_respect

,tweet_id_comment_nr,text_cleaned_02,majority_vote_respect
0,151_2,Waarin Natalie en Nigel de wereld bespreken en...,1.0
1,203_5,Klimaatwetenschappers hebben een ander vakgebi...,1.0
2,349_5,En verder wordt er gezegd dat vervuiling een b...,1.0
3,311_5,Hoi Marien. Bedoeld voor de GroenLinks. Zie he...,1.0
4,105_4,Zeker. En anders exporteren we dat spul naar A...,1.0
...,...,...,...
1555,252_1,Natuurlijk wel.,0.0
1556,347_3,"Broeikaseffect, lang niet meer gehoord 😃\n\nIk...",1.0
1557,249_2,"Ik vind discussies over Media Bias waardevol, ...",1.0
1558,367_2,Dat staat in het artikel. Plantengroei explode...,1.0
1559,124_8,"Zeker, #au!",1.0

✅ Draw 500 samples
✅ Each sample contains 10 texts, 5 with annotation == 1, 5 with annotation == 0
✅ Sampling is with replacement across samples
✅ Texts can appear multiple times across different samples (bootstrapping style)
✅ But each sample still contains 10 unique texts (no duplicates within a sample)

In [11]:
# Step 1: Split the dataset by annotation 0/1
texts_1 = df_female_train_respect[df_female_train_respect['majority_vote_respect'] == 1]['text_cleaned_02'].unique()
texts_0 = df_female_train_respect[df_female_train_respect['majority_vote_respect'] == 0]['text_cleaned_02'].unique()


# Sanity check
assert len(texts_1) >= 5 and len(texts_0) >= 10, "Not enough texts in each class."

# Step 2: Draw 500 samples of 10 texts per class
samples_1 = []
samples_0 = []

for _ in range(500):
    sample_1 = np.random.choice(texts_1, size=10, replace=False)
    sample_0 = np.random.choice(texts_0, size=10, replace=False)
    samples_1.append(sample_1)
    samples_0.append(sample_0)

# Step 3: Convert to DataFrames
bootstrap_1_df = pd.DataFrame(samples_1, columns=[f'text_1_{i+1}' for i in range(10)])
bootstrap_0_df = pd.DataFrame(samples_0, columns=[f'text_0_{i+1}' for i in range(10)])

# ✅ Done!
print("Annotation = 1 Samples:", len(bootstrap_1_df))

print("\nAnnotation = 0 Samples:", len(bootstrap_0_df))

Annotation = 1 Samples: 500

Annotation = 0 Samples: 500

In [12]:
bootstrap_0_df.head()

,text_0_1,text_0_2,text_0_3,text_0_4,text_0_5,text_0_6,text_0_7,text_0_8,text_0_9,text_0_10
0,DE MAN IS ECHT EEN AAN EEN AANSTORMWAAING,DE MAN IS EEN ORKAANFLUITING!,wat is er onjuist?,"Aah, we nemen het International Climate Change...",Ik bespeur nog steeds geen (begin van een) opl...,Ja je blijft er om lachen om die dwazen 😂😂😂 va...,Ik heb hem echt wel gezien hoor. Maar ik vond ...,Knap hoor. Ik heb ook gewoon een academische s...,"Je wilt luievrouwen, je wilt driekus, je wilt ...",Uw grootheid is ongekend ongetwijfeld. Maar da...
1,Waarom doe je alsof dit een uitspraak van poli...,Hij praat trouwens onzin want ik heb hier tig ...,Wat een domme tweet....,Helemaal fijn pik. Voortaan lekker je mening v...,Ferd is een idioot en heeft de ballen verstand...,Of hier,Denk je dat ik als marketeer niet overal een a...,"""simpele zieltjes als jou ... echt W.B. ""als j...",Tegen zoveel onbenul valt niet op te boksen🤷‍♂️,Omdat u kunt vliegen bent u wetenschapper op d...
2,Beste Hibma\n\nJe gaan nogal blind op wetensch...,De Belgische uitgerangeerde natuurkundige die ...,Tegen zoveel onbenul valt niet op te boksen🤷‍♂️,Waarom doe je alsof dit een uitspraak van poli...,Je woont aan zee is niet echt iets wat je expe...,Hun weer programma gaat met horten en stoten z...,Hij vertelt dat er vaker overstromingen gewees...,Linkse mafkees.,Wat bewijst de grafiek? Dat heb ik van jou nog...,Kletskoek
3,DENK JE ECHT??? ER WORDT MET WILLEKEUR GEKNOEI...,Het eerste is niet waar...,Wat bewijst de grafiek? Dat heb ik van jou nog...,Ah..check✅.. jij bent af!\n\nTweetje was corre...,Dream on,Milancovitsch?,Maar je hoort wel bij een steeds kleinere mind...,Zodra u uw eerste wetenschappelijk onderbouwde...,Wat begrijp je hier niet aan?\n\nDe Rijn zat a...,Nee helemaal niet je snapt er niets van
4,Kan je ook nog iets anders dan de man spelen ?...,Link staat eronder kiekoofd,Dus?\n\nPersonen zoals jij en degene die het a...,Wat begrijp je hier niet aan?\n\nDe Rijn zat a...,En jij kan dat objectief beoordelen? Heel bijz...,Kletskoek,"Gevolgen...\n\nHorende doof, ziende blind. Het...",Nee dus. Ik woon aan zee. Gelul.,Hij praat trouwens onzin want ik heb hier tig ...,wat is er onjuist?

In [13]:
bootstrap_1_df.head()

,text_1_1,text_1_2,text_1_3,text_1_4,text_1_5,text_1_6,text_1_7,text_1_8,text_1_9,text_1_10
0,Ik zie bij Gert Jan en anderen binnen de parti...,Snap ik. Was deels staand een optie geweest?,Mijn mening is dus dat de NOS juist tracht all...,"Wel een vieze, enorm vervuilende diesel toch?",Afgelopen februari!,Hahaha junior strous gang co2=ok,"Lauwe douche nemen, niet afdrogen, en op de 't...","😳Ja maar, NWO? HAARP? CO2 hoax?! Het is toch a...",Dat is goed nieuws!\nGefeliciteerd!\nEn tegeli...,Ja. Net één graad verwijderd van de perfecte 19
1,Dat kan ik snappen die gedachten. Die heb ik z...,"En dan de grote vraag als het om klimaat gaat,...",Dankje. Ik heb er ook over nagedacht. De jurid...,Zo 'dynamisch' zoals het nu is is het nog nooi...,Draadje even lezen,Dat is attent van je. Wat ben je toch een liev...,Heel erg.,Denk je ? Meeste politici wachten op een draag...,"Wat een onzin, er zijn genoeg initiatieven die...",Ah zelfs de knapste koppen op aarde kunnen dit...
2,Heb je gezien wat wij ( en ondergetekende) he...,Ja so? Je vraagt het verschil tussen vroeger (...,Nee ik snap IPCC WG1 best. Maar een causaal ve...,"Wat wil je met dat bericht zeggen, Gerard?",Zijn die doorrekeningen ergens openbaar?,"Dat was mijn verweer ook naar FB, maar ik denk...",Wow! Dus oma bezoek deed je in je zwembroek? 😂...,Dat de temperatuur op aarde schommelt is een n...,Dat is een kwestie van perspectief.,En Tata in India is schoner? Laten we daar beg...
3,ik heb geen idee hoe je 3 meter in 2100 in een...,Dus toch niet de koeien ?,"Nee, behanger las ik. Ook gevaarlijk 😅",[2/2] Kijken we naar de activiteit van onze zo...,Schiphol kan inderdaad niet zonder kerosine. D...,Prima. Als je maar niet van mening bent dat de...,Zeker. En anders exporteren we dat spul naar A...,en het is idd veelomvattend en complex. Zelfs ...,"Dan moet je bomen planten, vooral geen extra m...",Geen direct verband tussen individuele gebeurt...
4,"Ja, maar die koeling duurt geen 4000 jaar.",Dat kan. heb je een peer review van een deel v...,Was je daar ook betrokken bij de meteo?,China heeft ook eens geprobeerd het klimaat te...,"😳Ja maar, NWO? HAARP? CO2 hoax?! Het is toch a...",Niemand beweert dat elektrisch gaan fietsen al...,"Klopt, maar zal nu opmars gaan maken. Met alle...","Is in 2019 in Australië uitgezocht, 85% van de...",ER WORDEN ONS OOK VEEL DINGEN WIJSGEMAAKT DOOR...,De zondvloed komt er niet weer volgens de Bijbel

🔁 Generate 500 distinct few-shot prompts, where each one is built from:

One row from df_0 (10 examples of class 0)

One row from df_1 (10 examples of class 1)

💾 And save each prompt as a separate JSON file for use later during classification.

In [21]:
import json
#import os

def generate_fewshot_sets(df_0, df_1, output_dir="fewshot_sets_female_respect"):
    os.makedirs(output_dir, exist_ok=True)

    for i in range(len(df_0)):
        fewshot = []

        # System message
        fewshot.append({
            "role": "system",
            "content": "You are a classification algorithm that has to differentiate between respectful and not respectful user comments in Dutch, where respectful is 1 and not respectful is 0. Answer with the correct class only. You must answer every time."
        })

        # Positive examples (label 1) from df_1
        for text in df_1.iloc[i]:
            fewshot.append({
                "role": "user",
                "content": f"{text} + categories: 1, 0"
            })
            fewshot.append({
                "role": "assistant",
                "content": "1"
            })

        # Negative examples (label 0) from df_0
        for text in df_0.iloc[i]:
            fewshot.append({
                "role": "user",
                "content": f"{text} + categories: 1, 0"
            })
            fewshot.append({
                "role": "assistant",
                "content": "0"
            })

        # Save to JSON file
        with open(os.path.join(output_dir, f"fewshot_{i}.json"), "w", encoding="utf-8") as f:
            json.dump(fewshot, f, ensure_ascii=False, indent=2)

    print(f"✅ Saved {len(df_0)} few-shot combinations to '{output_dir}/'")

In [22]:
generate_fewshot_sets(bootstrap_0_df, bootstrap_1_df)

✅ Saved 500 few-shot combinations to 'fewshot_sets_female_respect/'

In [24]:
# Test the first
with open("fewshot_sets_female_respect/fewshot_0.json", "r", encoding="utf-8") as f:
    fewshot_0 = json.load(f)

# Show it nicely
for message in fewshot_0:
    print(f"{message['role'].upper()}: {message['content']}\n")

SYSTEM: You are a classification algorithm that has to differentiate between respectful and not respectful user comments in Dutch, where respectful is 1 and not respectful is 0. Answer with the correct class only. You must answer every time.

USER: Ik zie bij Gert Jan en anderen binnen de partij zoals Carla Dik-Faber, Anja Haga, etc, al heel lang die drive op dit onderwerp, gelukkig. En toch: waarom kon het kabinet gisteren reageren met de stelling dat ze andere landen op hun verantwoordelijkheid gingen aanspreken. &gt; + categories: 1, 0

ASSISTANT: 1

USER: Snap ik. Was deels staand een optie geweest? + categories: 1, 0

ASSISTANT: 1

USER: Mijn mening is dus dat de NOS juist tracht alles zo objectief mogelijk te brengen zonder zaken waar vooroordelen over bestaan te benoemen! Ook subjectief! + categories: 1, 0

ASSISTANT: 1

USER: Wel een vieze, enorm vervuilende diesel toch? + categories: 1, 0

ASSISTANT: 1

USER: Afgelopen februari! + categories: 1, 0

ASSISTANT: 1

USER: Hahaha junior strous gang co2=ok + categories: 1, 0

ASSISTANT: 1

USER: Lauwe douche nemen, niet afdrogen, en op de 'tocht' gaan staan bij open raam. Dat koelt wel af. + categories: 1, 0

ASSISTANT: 1

USER: 😳Ja maar, NWO? HAARP? CO2 hoax?! Het is toch allemaal een verdienmodel?! + categories: 1, 0

ASSISTANT: 1

USER: Dat is goed nieuws!
Gefeliciteerd!
En tegelijk verdrietig - dat deze weg nodig was + categories: 1, 0

ASSISTANT: 1

USER: Ja. Net één graad verwijderd van de perfecte 19 + categories: 1, 0

ASSISTANT: 1

USER: DE MAN IS ECHT EEN AAN EEN AANSTORMWAAING + categories: 1, 0

ASSISTANT: 0

USER: DE MAN IS EEN ORKAANFLUITING! + categories: 1, 0

ASSISTANT: 0

USER: wat is er onjuist? + categories: 1, 0

ASSISTANT: 0

USER: Aah, we nemen het International Climate Change Panel dus alleen serieus mbt hun rampmodellen/ worst case scenarios!? + categories: 1, 0

ASSISTANT: 0

USER: Ik bespeur nog steeds geen (begin van een) oplossing. Gewoon maar niks doen? + categories: 1, 0

ASSISTANT: 0

USER: Ja je blijft er om lachen om die dwazen 😂😂😂 van de zomer word het helemaal lachen als de zon schijnt in juli en augustus dat kan niet 😂😂 + categories: 1, 0

ASSISTANT: 0

USER: Ik heb hem echt wel gezien hoor. Maar ik vond het vrij eenzijdig en gedateerd. + categories: 1, 0

ASSISTANT: 0

USER: Knap hoor. Ik heb ook gewoon een academische studie afgerond. Dus ben prima in staat zelf na te denken en me geen ongefundeerde angsten te laten aanpraten. Klimaat is een verdienmodel geworden. #followthemoney + categories: 1, 0

ASSISTANT: 0

USER: Je wilt luievrouwen, je wilt driekus, je wilt warmte, je wilt een palmboom...

Hier: + categories: 1, 0

ASSISTANT: 0

USER: Uw grootheid is ongekend ongetwijfeld. Maar dat verandert de facts niet. + categories: 1, 0

ASSISTANT: 0

### 3. Specifiy 500 Few-Shot Models

In [27]:
from tqdm import tqdm

def prepare_fewshot_test_prompts_flat(fewshot_dir, test_comments, output_dir="models"):
    os.makedirs(output_dir, exist_ok=True)

    for i in tqdm(range(500), desc="Creating model files"):
        # Load few-shot base prompt
        with open(os.path.join(fewshot_dir, f"fewshot_{i}.json"), "r", encoding="utf-8") as f:
            base_prompt = json.load(f)

        # For each test comment, create a full prompt
        full_prompts = []
        for comment in test_comments:
            prompt = base_prompt + [{
                "role": "user",
                "content": f"{comment} + categories: 1, 0"
            }]
            full_prompts.append(prompt)

        # Save all test prompts for this model in one file
        with open(os.path.join(output_dir, f"model_{i:03d}.json"), "w", encoding="utf-8") as f:
            json.dump(full_prompts, f, ensure_ascii=False, indent=2)

    print(f"✅ Done! Saved 500 converted few-shot test sets in '{output_dir}/'")

In [16]:
df_female_test = pd.read_csv("df_female_test.csv")
df_female_test

,tweet_id_comment_nr,text,majority_vote_respect,majority_vote_attack,majority_vote_argument,text_cleaned_01,text_cleaned_02
0,316_7,"@USER @USER Over 6 jaar 1,5⁰, zó heftig? Dan z...",1.0,0.0,1.0,"Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie...","Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowie..."
1,479_1,@USER Dat punt van die klimaatverandering is n...,1.0,0.0,0.0,Dat punt van die klimaatverandering is nu wel ...,Dat punt van die klimaatverandering is nu wel ...
2,151_1,@USER Ik voel een nieuw podcast opkomen: “Mijn...,1.0,0.0,0.0,Ik voel een nieuw podcast opkomen: “Mijn kappe...,Ik voel een nieuw podcast opkomen: “Mijn kappe...
3,311_3,@USER Zaterdagochtend 12-2-22. Blauwe lucht. V...,1.0,0.0,1.0,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...,Zaterdagochtend 12-2-22. Blauwe lucht. Vliegtu...
4,513_7,@USER @USER klimaatontkenner=#misinformatie ht...,0.0,0.0,0.0,klimaatontkenner=#misinformatie https://t.co/I...,klimaatontkenner=#misinformatie
...,...,...,...,...,...,...,...
385,249_4,"@USER Muah, ik weet niet of dat zo is. Ik heb ...",1.0,0.0,1.0,"Muah, ik weet niet of dat zo is. Ik heb veel s...","Muah, ik weet niet of dat zo is. Ik heb veel s..."
386,550_4,"@USER @USER @USER Utopisme en activisme, daare...",1.0,0.0,0.0,"Utopisme en activisme, daarentegen, lijken voo...","Utopisme en activisme, daarentegen, lijken voo..."
387,524_5,@USER Beter ten halve gekeerd hoor…🤔😀,1.0,0.0,1.0,Beter ten halve gekeerd hoor…🤔😀,Beter ten halve gekeerd hoor…🤔😀
388,568_8,@USER @USER @USER In alle grote kranten wordt ...,1.0,1.0,1.0,In alle grote kranten wordt klimaatverandering...,In alle grote kranten wordt klimaatverandering...
389,204_1,@USER @USER Hier heb je ruim 31 duizend rockst...,0.0,0.0,0.0,Hier heb je ruim 31 duizend rocksterren:\nhttp...,Hier heb je ruim 31 duizend rocksterren:\n\nHo...

In [29]:
# test_comments should be a list of all test inputs
# e.g., test_comments = test_df["text_cleaned_02"].tolist()

prepare_fewshot_test_prompts_flat("fewshot_sets_female_respect", df_female_test["text_cleaned_02"].tolist())

Creating model files: 100%|███████████████████| 500/500 [00:23<00:00, 20.85it/s]

✅ Done! Saved 500 few-shot test sets in 'models/'

In [35]:
# Read first
with open("models/model_000.json", "r", encoding="utf-8") as f:
    model_0_data = json.load(f)
len(model_0_data)

390

In [33]:
model_0_data[0] # first comment

[{'role': 'system',
  'content': 'You are a classification algorithm that has to differentiate between respectful and not respectful user comments in Dutch, where respectful is 1 and not respectful is 0. Answer with the correct class only. You must answer every time.'},
 {'role': 'user',
  'content': 'Ik zie bij Gert Jan en anderen binnen de partij zoals Carla Dik-Faber, Anja Haga, etc, al heel lang die drive op dit onderwerp, gelukkig. En toch: waarom kon het kabinet gisteren reageren met de stelling dat ze andere landen op hun verantwoordelijkheid gingen aanspreken. &gt; + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Snap ik. Was deels staand een optie geweest? + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Mijn mening is dus dat de NOS juist tracht alles zo objectief mogelijk te brengen zonder zaken waar vooroordelen over bestaan te benoemen! Ook subjectief! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Wel een vieze, enorm vervuilende diesel toch? + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user', 'content': 'Afgelopen februari! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Hahaha junior strous gang co2=ok + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': "Lauwe douche nemen, niet afdrogen, en op de 'tocht' gaan staan bij open raam. Dat koelt wel af. + categories: 1, 0"},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': '😳Ja maar, NWO? HAARP? CO2 hoax?! Het is toch allemaal een verdienmodel?! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Dat is goed nieuws!\nGefeliciteerd!\nEn tegelijk verdrietig - dat deze weg nodig was + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Ja. Net één graad verwijderd van de perfecte 19 + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'DE MAN IS ECHT EEN AAN EEN AANSTORMWAAING + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'DE MAN IS EEN ORKAANFLUITING! + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user', 'content': 'wat is er onjuist? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Aah, we nemen het International Climate Change Panel dus alleen serieus mbt hun rampmodellen/ worst case scenarios!? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ik bespeur nog steeds geen (begin van een) oplossing. Gewoon maar niks doen? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ja je blijft er om lachen om die dwazen 😂😂😂 van de zomer word het helemaal lachen als de zon schijnt in juli en augustus dat kan niet 😂😂 + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ik heb hem echt wel gezien hoor. Maar ik vond het vrij eenzijdig en gedateerd. + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Knap hoor. Ik heb ook gewoon een academische studie afgerond. Dus ben prima in staat zelf na te denken en me geen ongefundeerde angsten te laten aanpraten. Klimaat is een verdienmodel geworden. #followthemoney + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Je wilt luievrouwen, je wilt driekus, je wilt warmte, je wilt een palmboom... \n\nHier: + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Uw grootheid is ongekend ongetwijfeld. Maar dat verandert de facts niet. + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Over 6 jaar 1,5⁰, zó heftig? Dan zijn we sowieso verloren. Een bouwplan voorbereiden kost hier al gemiddeld 10 jaar. Zelfs wat normen een beetje aanscherpen kost ons al vele jaren. Hoe gaan we hier ooit nog enige grip op krijgen? \n(Wie zegt dat waar?). + categories: 1, 0'}]

In [36]:
model_0_data[389] # 390th comment

[{'role': 'system',
  'content': 'You are a classification algorithm that has to differentiate between respectful and not respectful user comments in Dutch, where respectful is 1 and not respectful is 0. Answer with the correct class only. You must answer every time.'},
 {'role': 'user',
  'content': 'Ik zie bij Gert Jan en anderen binnen de partij zoals Carla Dik-Faber, Anja Haga, etc, al heel lang die drive op dit onderwerp, gelukkig. En toch: waarom kon het kabinet gisteren reageren met de stelling dat ze andere landen op hun verantwoordelijkheid gingen aanspreken. &gt; + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Snap ik. Was deels staand een optie geweest? + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Mijn mening is dus dat de NOS juist tracht alles zo objectief mogelijk te brengen zonder zaken waar vooroordelen over bestaan te benoemen! Ook subjectief! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Wel een vieze, enorm vervuilende diesel toch? + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user', 'content': 'Afgelopen februari! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Hahaha junior strous gang co2=ok + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': "Lauwe douche nemen, niet afdrogen, en op de 'tocht' gaan staan bij open raam. Dat koelt wel af. + categories: 1, 0"},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': '😳Ja maar, NWO? HAARP? CO2 hoax?! Het is toch allemaal een verdienmodel?! + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Dat is goed nieuws!\nGefeliciteerd!\nEn tegelijk verdrietig - dat deze weg nodig was + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'Ja. Net één graad verwijderd van de perfecte 19 + categories: 1, 0'},
 {'role': 'assistant', 'content': '1'},
 {'role': 'user',
  'content': 'DE MAN IS ECHT EEN AAN EEN AANSTORMWAAING + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'DE MAN IS EEN ORKAANFLUITING! + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user', 'content': 'wat is er onjuist? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Aah, we nemen het International Climate Change Panel dus alleen serieus mbt hun rampmodellen/ worst case scenarios!? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ik bespeur nog steeds geen (begin van een) oplossing. Gewoon maar niks doen? + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ja je blijft er om lachen om die dwazen 😂😂😂 van de zomer word het helemaal lachen als de zon schijnt in juli en augustus dat kan niet 😂😂 + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Ik heb hem echt wel gezien hoor. Maar ik vond het vrij eenzijdig en gedateerd. + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Knap hoor. Ik heb ook gewoon een academische studie afgerond. Dus ben prima in staat zelf na te denken en me geen ongefundeerde angsten te laten aanpraten. Klimaat is een verdienmodel geworden. #followthemoney + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Je wilt luievrouwen, je wilt driekus, je wilt warmte, je wilt een palmboom... \n\nHier: + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Uw grootheid is ongekend ongetwijfeld. Maar dat verandert de facts niet. + categories: 1, 0'},
 {'role': 'assistant', 'content': '0'},
 {'role': 'user',
  'content': 'Hier heb je ruim 31 duizend rocksterren:\n\nHoe heten die van jou? + categories: 1, 0'}]